title: my awesome title
author: GitHub lukeoson
email: lukeoson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  here is an awesome description for my new site. i can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: lukeoson # DO NOT include the @ character, or else the build will fail!
github_username:  lukeoson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
